### ISSUE TITLE
Unity BodyTracking Sample catching exception for background thread result = K4A_RESULT_FAILED

### ISSUE THREAD

**Issue by naotoerg** [microsoft/Azure-Kinect-Sensor-SDK#1600]
**Describe the bug**

unity Example stops at init, catching exception for background thread result = K4A_RESULT_FAILED 

I have found possible typo on MoveLibraryFiles.bat.
`
copy %BODY_TRACKING_TOOLS_PATH%cudnn64_cnn_infer64_8.dll./
copy %BODY_TRACKING_TOOLS_PATH%cudnn64_ops_infer64_8.dll 
`
Azure Kinect Body Tracking SDK did not have such two files.
But it had 

```
cudnn_ops_infer64_8.dll
cudnn_cnn_infer64_8.dll
```

Unfortunately fixing these two possible typo didn't fix the K4A_RESULT_FAILED issue.

![SharedScreenshot png](https://user-images.githubusercontent.com/13324152/118579736-9a4d5180-b7c9-11eb-9e24-3f0d610fb994.jpg)

  
**To Reproduce**
Execute all the steps on the readme.
open sample scene on unity and play.

**Desktop (please complete the following information):**
 - OS with Version:Windows 19042.928 
 - SDK Version: Azure Kinect SDK v1.4.1 / Azure Kinect Body Tracking SDK v1.1.0 
 - Firmware version:  Current Firmware Versions:
  RGB camera firmware:      1.6.102
  Depth camera firmware:    1.6.75
  Depth config file:        6109.7
  Audio firmware:           1.6.14
  Build Config:             Production
-Unity Version: 2019.1.14f1

**Additional context**
k4aviewer and k4abt_simple_3d_viewer works flawlessly.

**Comment by naotoerg** [comment]
I got the sample project working.
Not really a solution but, I copied all the dlls from the SDK to the unity project and now it works.
I assume that the batch file is missing some files to copy.

**Comment by WhimsicalToyBox** [comment]
It's not a radical measure, but if you use ```TrackerProcessingMode.Cuda``` instead of ```TrackerProcessingMode.Gpu``` when initializing Tracker, it will work for the time being.

https://github.com/microsoft/Azure-Kinect-Samples/blob/master/body-tracking-samples/sample_unity_bodytracking/Assets/Scripts/SkeletalTrackingProvider.cs#L46

**Comment by naotoerg** [comment]
> It's not a radical measure, but if you use `TrackerProcessingMode.Cuda` instead of `TrackerProcessingMode.Gpu` when initializing Tracker, it will work for the time being.
> 
> https://github.com/microsoft/Azure-Kinect-Samples/blob/master/body-tracking-samples/sample_unity_bodytracking/Assets/Scripts/SkeletalTrackingProvider.cs#L46

Thank you for the tip!
Cuda mode works a lot faster then GPU mode!

To run the sample in Cuda mode, you still need to copy some dlls by hand.

copying these three from the SDK folder to the root of the project worked for me
```
cudnn_ops_infer64_8.dll
cudnn_cnn_infer64_8.dll
cufft64_10.dll
```

**Comment by UnaNancyOwen** [comment]
This problem will be solved with https://github.com/microsoft/Azure-Kinect-Samples/pull/62.
